
CREATE TABLE Usuario (
  idUsuario INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Carrera_Clave VARCHAR(25) NOT NULL,
  Nombre VARCHAR(25) NOT NULL UNIQUE,
  Contrasenia VARCHAR(50) NULL,
  Nombre_Cola VARCHAR(150) NOT NULL,
  PRIMARY KEY(idUsuario)
);


